create table fruit (
    id bigint generated by default as identity,
    price float not null,
    quantity integer not null,
    type varchar(255),
    weight float not null,
    primary key (id)
);



INSERT INTO FRUIT (type, price, weight, quantity) VALUES ('Grape', 3, 100, 12);
INSERT INTO FRUIT (type, price, weight, quantity) VALUES ('Orange', 1, 45, 10);
INSERT INTO FRUIT (type, price, weight, quantity) VALUES ('Pineapple', 5, 300, 5);
INSERT INTO FRUIT (type, price, weight, quantity) VALUES ('Melon', 4, 250, 6);
INSERT INTO FRUIT (type, price, weight, quantity) VALUES ('Banana', 0.75, 30, 5);
INSERT INTO FRUIT (type, price, weight, quantity) VALUES ('Watermelon', 6, 450, 4);
INSERT INTO FRUIT (type, price, weight, quantity) VALUES ('Blueberry', 4.50, 100, 10);
INSERT INTO FRUIT (type, price, weight, quantity) VALUES ('Strawberry', 2.50, 300, 10);
INSERT INTO FRUIT (type, price, weight, quantity) VALUES ('Mango', 3.50, 100, 10);
INSERT INTO FRUIT (type, price, weight, quantity) VALUES ('Apple', 2, 50, 12);